version: '3.3'

services:
  frontend:
    build: ./frontend
    ports:
      - 8501:8501
    network_mode: bridge


  backend:
    build: ./backend
    ports:
      - 8000:8000
    network_mode: bridge

volumes:
  assignemnt-02: