name: Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    name: PyTest Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
          restore-keys: | 
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install -e ./backend/

      - name: Run Testcases
        env:
         AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
         AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
         TARGET_BUCKET_NAME: ${{ secrets.TARGET_BUCKET_NAME }}
         ALGORITHM: ${{ secrets.ALGORITHM }}
         ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: | 
          pytest
          
  deploy:
    name: Deploying
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
              cd /home/ubuntu/Assignment-02
              rm GOESmetadata.db
              git checkout main
              git fetch --all
              git reset --hard origin/main
              git pull origin main
              sudo su
              docker-compose down
              docker-compose build --no-cache
              docker-compose up -d
          